version: "3.9"

services:

  postgres:
    image: postgres
    container_name: clinica-postgres-container
    environment:
      POSTGRES_USER: usuario_teste
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: meubancoclinica
    ports:
      - "5432:5432"
    networks:
      - backend

  app:
    build: .
    container_name: clinica-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge